### ISSUE TITLE
Turning around the ball

### ISSUE THREAD

**Issue by MattGen** [UniVR/GolfVR#1]
1 - After turning around the ball, shooting it propulses it in the same direction as if I never turned around at all
2 - Turning around the ball decreases the loading potential of the shoot
3 - Once the ball has been shot, I still can turn around it, so that I can travel on the map.

**Comment by ludo6577** [comment]
Ok i will take a look at this issue, thx

**Comment by ludo6577** [comment]
Fixed in commit: https://github.com/ludo6577/GolfVR/commit/3d9b658f44f06ef587e7f58e0d84aed3d482adb4
