### ISSUE TITLE
Creating the 18 holes

### ISSUE THREAD

**Issue by ludo6577** [UniVR/GolfVR#12]
Creating the 18 holes and it's relative terrain object.
see with @3mmanuelB

**Comment by ludo6577** [comment]
@MattGen & @3mmanuelB :
Is this issue related to (deleted) milestone: Creating 18 greens (Creating a green for each hole) ?

**Comment by MattGen** [comment]
"Creating 18 greens (Creating a green for each hole) ?"
Partially, remember we have to find a way to create holes, because we don't wan't to mess up with the Terrain collider

**Comment by MattGen** [comment]
Do we consider the current terrains as good enough to close this issue ?

**Comment by MattGen** [comment]
Closed by waiting for better results
