### ISSUE TITLE
Wind mechanics (Physics/Coding)

### ISSUE THREAD

**Issue by ludo6577** [UniVR/GolfVR#14]
Add a Wind mechanics with physics of Unity

**Comment by ludo6577** [comment]
See with @MattGen in order to link with the GUI (https://github.com/ludo6577/GolfVR/issues/15)

**Comment by MattGen** [comment]
We thought about integrating an anemometer to show the wind's force and direction.

**Comment by ludo6577** [comment]
Anemometer and random wind force done. Some minor modification should be added later
