### ISSUE TITLE
Environment sound

### ISSUE THREAD

**Issue by ludo6577** [UniVR/GolfVR#19]
Having a single environment sound, as a bird whistling.

**Comment by MattGen** [comment]
@ludo6577 If help required

**Comment by ludo6577** [comment]
@3mmanuelB Are you still on it?

**Comment by MattGen** [comment]
@3mmanuelB Are you still with us ? We're on the move !
Laisse pas fuir le taureau chope lui les cornes !

**Comment by ludo6577** [comment]
One sound has been added (enough for this first version of the game)
