### ISSUE TITLE
Shooting power increases each shot

### ISSUE THREAD

**Issue by MattGen** [UniVR/GolfVR#2]
Shooting power increases each shot. 
UI for turning around should re-appear when player is ready to make a new shot.

**Comment by ludo6577** [comment]
Theses issues must have been in two different issues...
I will have a look at those tomorrow thx

**Comment by ludo6577** [comment]
fixed in commit: https://github.com/ludo6577/GolfVR/commit/82a79cc3b1b6e43466d919cabf454c7e395712fc
