### ISSUE TITLE
Modeling Trees & texturing them

### ISSUE THREAD

**Issue by MattGen** [UniVR/GolfVR#23]
'Cause we need to have a beautiful environment

**Comment by ludo6577** [comment]
Yes we need it ! ^^ But with really low poly, that's what is going to be hard

**Comment by MattGen** [comment]
OK I have to move my own ass before summer ends !

**Comment by ludo6577** [comment]
Winter is coming ! (GOT joke)
We need less tree in order to improve performances, see: https://github.com/UniVR/GolfVR/issues/26

**Comment by MattGen** [comment]
yup, current trees are just there for testing purposes.

**Comment by MattGen** [comment]
I can't manage to have the trees standing Y-Up -_-. But here's how the 2nd tree looks
![untitled](https://cloud.githubusercontent.com/assets/8799606/9774645/28aed0f2-574a-11e5-9508-5f0f876e2ff7.png)
