### ISSUE TITLE
Re-Modeling & texturing the clubs

### ISSUE THREAD

**Issue by MattGen** [UniVR/GolfVR#24]
'Cause they're the closest thing the player has in sight.

**Comment by MattGen** [comment]
Is this a (Pre-Beta) feature or should I create a new milestone "(Beta) Modeling" ?

**Comment by ludo6577** [comment]
@MattGen I think it should stay in Pre-Beta, we can't show clubs like that, polygones are too obvious in this version and it won't take long to get the news ones, isn't it?

**Comment by ludo6577** [comment]
Changed labels to bug with priority normal

**Comment by MattGen** [comment]
I'm halfway on that issue  !
