### ISSUE TITLE
Performance issue !

### ISSUE THREAD

**Issue by ludo6577** [UniVR/GolfVR#26]
Reduce draw calls to the minimum ! We need to try: https://www.assetstore.unity3d.com/en/#!/content/582

**Comment by ludo6577** [comment]
see: http://indiedevspot.com/2014/03/12/optimizing-mobile-games-in-unity/

**Comment by MattGen** [comment]
Irrelevent comment edited.

**Comment by MattGen** [comment]
Changed this issue's milestone to "1st Release milestone" : Performance is something we have to care all along the developping process.

**Comment by MattGen** [comment]
Performance is a permanent concern.

**Comment by ludo6577** [comment]
For the moment performances are good
