### ISSUE TITLE
Difficulty /!\ Level

### ISSUE THREAD

**Issue by MattGen** [UniVR/GolfVR#34]
Wind speed depend of:
_ depends on terrain/hole (1 easy, 10 hard) => different weather for each hole?
_ And player can select his mode
_The harder the difficulty mode, the less information is shown to the player.

**Comment by ludo6577** [comment]
_For each hole define a range for the wind (Wind min/max)
_The MainScript difficulty will modify this previously defined range
Example: if we have 3 difficulties (easy, medium, hard) for an range of [0; 10] then we will have a random wind in the range: easy [0; 3.33], medium [3.33; 6.66], hard [6.66; 10]
