### ISSUE TITLE
Explain rules and safety instructions in the introduction

### ISSUE THREAD

**Issue by ludo6577** [UniVR/GolfVR#40]
Explain the rules before the game begin
_Have some place to play (as the Wii introduction for the wiimote)
_Watch the ball to shoot (the time the ball is watched will define the power)
_... (to be defined)

**Comment by ludo6577** [comment]
link to issue: https://github.com/UniVR/GolfVR/issues/30

**Comment by MattGen** [comment]
"Have some place to play (as the Wii introduction for the wiimote)"
We totally need this !

"Watch the ball to shoot (the time the ball is watched will define the power)"
Why not planning on a small interactive tutorial as the player launches his first game ?

**Comment by ludo6577** [comment]
The firsts levels are the same as a tutorial, the level will be really low

**Comment by MattGen** [comment]
Yes, but we could add at the first playing session some advices on how to play. (And many mobile games contains advices or jokes on loading screens)

**Comment by MattGen** [comment]
Improvments needed on this !

**Comment by ludo6577** [comment]
Specifications changed
