### ISSUE TITLE
Better render for the hole's flag

### ISSUE THREAD

**Issue by ludo6577** [UniVR/GolfVR#41]
We do not see the end flag very well. A GUI that show the distance with the player can be a solution (as seen in other golf games)

**Comment by MattGen** [comment]
yup, first the flag needs a texture, second, haven't we got an issue about difficulty, saying that the harder the play mode, the less information is shown to the player (example : easy mode -> enabling that little GUI thing you're talking about, hard mode -> the less GUI/info enabled for the player)

**Comment by ludo6577** [comment]
Yes we can do something like that but it is not a priority. We will see to adapt the GUI on the difficulty on the next version
