### ISSUE TITLE
Code for the main menu

### ISSUE THREAD

**Issue by ludo6577** [UniVR/GolfVR#45]
Enter the level
Exit the game
Choosing level (easy, medium, hard, ...)
Choosing hole ?
Some other game parameters

See issue: https://github.com/UniVR/GolfVR/issues/30

**Comment by MattGen** [comment]
I suggest something like that :
Main menu :
 ->18 holes -> difficulty modes
 -> 9 holes -> from hole 1 to 9 or from hole 9 to 18 -> difficulty modes
-> training -> choosing hole -> wind power

**Comment by MattGen** [comment]
(and why not : unlockable difficulty mode : crazy !!! = wind is totally random)

**Comment by MattGen** [comment]
There's still some improvments to do.

**Comment by ludo6577** [comment]
Everyting now done by Animators
