### ISSUE TITLE
Tree issue ! 

### ISSUE THREAD

**Issue by ludo6577** [UniVR/GolfVR#46]
When we shoot the ball we can finish in a tree
_add tree collision
_or add some code that get out of the tree

**Comment by MattGen** [comment]
Do we just need to add a collider to the trees prefabs or enabling tree colliders on the terrain object should be sufficient ?

**Comment by ludo6577** [comment]
@MattGen maybe just enable tree colliders on the terrain is enough

**Comment by MattGen** [comment]
Nope, I think they all are enabled, I think we need a collider component on the prefab

**Comment by ludo6577** [comment]
The simpler the colider is, the better performance will be. can we just set a cylinder collider?

**Comment by MattGen** [comment]
I thougt using the LOD2 (less detailed) tree mesh

**Comment by MattGen** [comment]
Mesh collider isn't supported with terrain objects. I guess the problem comes from the texture i've added under the trees : it isn't understood as an out-of-bound texture. I'll remove it.

**Comment by MattGen** [comment]
Preview
![tree](https://cloud.githubusercontent.com/assets/8799606/9742953/e114375a-5663-11e5-9f92-13522fa99b11.png)

**Comment by MattGen** [comment]
![tree](https://cloud.githubusercontent.com/assets/8799606/9743795/73101706-5668-11e5-8ee1-2581cbe78055.png)

**Comment by MattGen** [comment]
Not at all what I was thinking at first, but way more convenient !
