### ISSUE TITLE
Light works

### ISSUE THREAD

**Issue by MattGen** [UniVR/GolfVR#49]
After integration is complete, lightning have to be refined.

**Comment by everlightmfg** [comment]
<a href="http://www.everlightmfg.com/lighting/led-work-light/">LED work light</a>
<a href="http://www.everlightmfg.com/product/led-stick-work-light-elm-8179/">LED Stick Work Light</a>
<a href="http://www.everlightmfg.com/product/pivoting-work-light-elm-8159/">Pivoting Work Light</a>
<a href="http://www.everlightmfg.com/product/led-trouble-light-elm-8032/">LED Trouble Light</a>
<a href="http://www.everlightmfg.com/product/led-pocket-light-elm-8191/">LED Pocket Light</a>

**Comment by MattGen** [comment]
Changed label from "Priority:high" to "Priority:normal" : as it is one of the last steps before building a release, it is less a priority than any other graphics-related issue. (I don't even understand why I added "priority:high" in the first place)

**Comment by MattGen** [comment]
EDITED
@ludo6577 This should (NOT :'( ) resolve the tree issue.
Ok, we can't wait for a patch release that may never come !

**Comment by MattGen** [comment]
@ludo6577 
https://gist.github.com/rmalecki/5fe4092b6b739209061b 
(I commented below)

**Comment by MattGen** [comment]
re-opened for next release : baking have to be done again.

**Comment by MattGen** [comment]
closing for tomorrow's release.
