### ISSUE TITLE
GUI should be displayed in front of everything

### ISSUE THREAD

**Issue by ludo6577** [UniVR/GolfVR#54]
The GUI (for example the out of bound panel) is shown behind some environment objects

**Comment by MattGen** [comment]
I don't know what to do with this, I agree with this idea for the out-of-bounds panel and the reticle/powerbar, but for the flag I do not. (partially hiding the flag on some cases is part of the gameplay)

**Comment by MattGen** [comment]
As we currently have no negative feedback on this, I'll set this under the Futur feature milestone.

**Comment by ludo6577** [comment]
Not a problem anymore
