### ISSUE TITLE
Ball direction indicator (GUI)

### ISSUE THREAD

**Issue by ludo6577** [UniVR/GolfVR#55]
Add a little GUI indicator that show the direction the ball will have after a shot

![2015-09-17_13-25-25](https://cloud.githubusercontent.com/assets/1528846/9932020/c22e42c0-5d40-11e5-8a7b-ae313a0b32a6.png)

**Comment by MattGen** [comment]
Sprite and basic integration complete ! Now it just needs to rotate !

**Comment by MattGen** [comment]
You'll see there was a smart logic to combine constraints and improvement of your idea ;)

**Comment by MattGen** [comment]
Sooo... now I guess it is clear ? I'll wait your point on it : is the current implement sufficient ?
I think it really improves readability of the interaction.
I suggest to disable it for difficulty mode : Hard

**Comment by ludo6577** [comment]
I moved the aiming arrow from the reticule to the ball so it don't move when the player move his head. See if it is good for you then close the issue. Everything else is fine for me ! :+1:
