### ISSUE TITLE
Hole plane texture is very apparent

### ISSUE THREAD

**Issue by ludo6577** [UniVR/GolfVR#71]
The hole texture/color/luminosity is very different from the green
![image](https://cloud.githubusercontent.com/assets/1528846/10556959/b82c4246-7496-11e5-8d7c-5a4c34586af1.png)

**Comment by MattGen** [comment]
This is even worst on the version i'm about to commit.
But I've spent the whole night on it.
For the third release there will be this slight difference as shown on your screenshot.
For tomorrow's (... this afternoon) release it will just be worst.
I've heard no player complaining about this.
I'm closing this issue.

**Comment by MattGen** [comment]
I'll get to fix this ! This won't be perfect but that'll work !
